import React from "react";

function ExternalLinks() {
  return (
    <div>
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/bootstrap.min.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/elegant-icons.min.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/all.min.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/animate.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/slick.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/slick-theme.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/nice-select.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/animate.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/default.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/style.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/responsive.css"
        media="all"
      />

      <link
        rel="stylesheet"
        type="text/css"
        href="assests/css/jquery.fancybox.min.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assests/css/nouislider.min.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/bootstrap.min.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/elegant-icons.min.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/all.min.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/animate.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/slick.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/slick-theme.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/nice-select.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/nouislider.min.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/animate.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/jquery.fancybox.min.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/flatpickr.min.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/default.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/style.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/responsive.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/bootstrap.min.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/elegant-icons.min.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/all.min.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/animate.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/slick.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/slick-theme.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/nice-select.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/nouislider.min.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/animate.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/jquery.fancybox.min.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/flatpickr.min.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/default.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/style.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/responsive.css"
        media="all"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="assets/css/intlTelInput.css"
        media="all"
      />
    </div>
  );
}

export default ExternalLinks;
